# Generated by Django 6.1.1 on 2026-09-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=160)),
                ('key', models.CharField(blank=True, max_length=128)),
                ('tier', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(max_length=64)),
                ('deliverable_met', models.BooleanField(default=False)),
                ('chart_confidence', models.FloatField(default=0.0)),
                ('chart_headers', models.JSONField(default=list)),
                ('chart_rows', models.JSONField(default=list)),
                ('lxml_path', models.TextField(blank=True)),
                ('selenium_xpath', models.TextField(blank=True)),
                ('selenium_css', models.TextField(blank=True)),
                ('egress_ip', models.CharField(blank=True, max_length=64)),
                ('proxy_type', models.CharField(blank=True, max_length=32)),
                ('html_path', models.CharField(blank=True, max_length=512)),
                ('screenshot_path', models.CharField(blank=True, max_length=512)),
                ('inspect_hits', models.JSONField(default=list)),
                ('raw_artifact', models.JSONField(default=dict)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_path', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at', '-created_at'],
            },
        ),
    ]
